apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myapp-db
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: myapp-aws
  target:
    name: myapp-db
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: dev/myapp/db
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myapp-redis
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: myapp-aws
  target:
    name: myapp-redis
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: dev/myapp/redis
      property: password